const DATA_URL="/data/latest.json";
let allStocks={};
let searchQuery="";
const $=id=>document.getElementById(id);
function escapeHTML(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function formatNumber(value,decimals=2){const n=Number(value);return Number.isFinite(n)?n.toLocaleString("en-BD",{minimumFractionDigits:decimals,maximumFractionDigits:decimals}):"—";}
function formatInteger(value){const n=Number(value);return Number.isFinite(n)?n.toLocaleString("en-BD",{maximumFractionDigits:0}):"—";}
function renderAllStocks(){const category=$("category-filter").value,status=$("status-filter").value,sort=$("sort-filter").value;const q=searchQuery.trim().toLowerCase();let stocks=Object.values(allStocks).filter(s=>{if(q&&!String(s.ticker).toLowerCase().includes(q)&&!String(s.company).toLowerCase().includes(q))return false;if(category!=="all"&&String(s.category||"")!==category)return false;const hasPrice=Number.isFinite(Number(s.price))&&Number(s.price)>0;if(status==="traded"&&!hasPrice)return false;if(status==="no-price"&&hasPrice)return false;return true;});stocks.sort((a,b)=>{if(sort==="company")return String(a.company).localeCompare(String(b.company));if(sort==="price-desc")return(Number(b.price)||-Infinity)-(Number(a.price)||-Infinity);if(sort==="price-asc")return(Number(a.price)||Infinity)-(Number(b.price)||Infinity);if(sort==="change-desc")return(Number(b.change_pct)||-Infinity)-(Number(a.change_pct)||-Infinity);if(sort==="change-asc")return(Number(a.change_pct)||Infinity)-(Number(b.change_pct)||Infinity);if(sort==="volume-desc")return(Number(b.volume)||-Infinity)-(Number(a.volume)||-Infinity);return String(a.ticker).localeCompare(String(b.ticker));});$("stock-count").textContent=stocks.length+" stocks";$("all-stocks-list").innerHTML=stocks.length?stocks.map(s=>{const hasPrice=Number.isFinite(Number(s.price))&&Number(s.price)>0,pct=Number(s.change_pct),change=Number.isFinite(pct)?(pct>0?"+":"")+formatNumber(pct)+"%":"—",changeClass=pct>0?"up":pct<0?"down":"";return '<button class="all-stock-row" type="button" data-ticker="'+escapeHTML(s.ticker)+'"><span class="stock-name-cell"><strong>'+escapeHTML(s.ticker)+'</strong><small>'+escapeHTML(s.company)+'</small></span><span><b class="category-mini category-'+escapeHTML(String(s.category||"").toLowerCase())+'">'+escapeHTML(s.category||"—")+'</b></span><span>'+(hasPrice?"৳ "+formatNumber(s.price):"—")+'</span><span class="'+changeClass+'">'+change+'</span><span>'+formatInteger(s.volume)+'</span></button>';}).join(""):'<div class="market-empty">No stocks match these filters.</div>';document.querySelectorAll(".all-stock-row").forEach(el=>el.addEventListener("click",()=>{window.history.pushState({stock:el.dataset.ticker},"","/stock/"+encodeURIComponent(el.dataset.ticker)); window.dispatchEvent(new PopStateEvent("popstate"));}));}
async function loadData(){try{const res=await fetch(DATA_URL+"?t="+Date.now());if(!res.ok)throw new Error();const payload=await res.json();allStocks=payload.stocks||{};$("last-updated").textContent=payload.updated_at?"Market data updated "+new Date(payload.updated_at).toLocaleString():"";renderAllStocks();}catch(e){}}
$("search-input").addEventListener("input",e=>{searchQuery=e.target.value;renderAllStocks();});$("category-filter").addEventListener("change",renderAllStocks);$("status-filter").addEventListener("change",renderAllStocks);$("sort-filter").addEventListener("change",renderAllStocks);
loadData();