// DSE Tracker frontend.
// Data is loaded from data/latest.json, which is generated by the Python scraper.

const DATA_URL = "data/latest.json";
let allStocks = {};
let currentData = null;
let currentRange = "1W";

const $ = (id) => document.getElementById(id);

async function loadData() {
  try {
    const res = await fetch(DATA_URL + "?t=" + Date.now());
    if (!res.ok) throw new Error("Failed to fetch market data");

    const payload = await res.json();
    allStocks = payload.stocks || {};

    const keepTicker = currentData?.ticker;
    const nextTicker = keepTicker && allStocks[keepTicker]
      ? keepTicker
      : payload.default_ticker;

    currentData = allStocks[nextTicker] || null;
    $("last-updated").dataset.updatedAt = payload.updated_at || "";
    render();

    $("status-badge").textContent = Object.keys(allStocks).length > 0
      ? "Data loaded"
      : "No data";
  } catch (err) {
    console.error(err);
    $("status-badge").textContent = "Data unavailable";
  }
}

function escapeHTML(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function selectStock(ticker) {
  if (!allStocks[ticker]) return;

  currentData = allStocks[ticker];
  currentRange = "1W";

  document.querySelectorAll(".range-tabs button").forEach((button) => {
    button.classList.toggle("active", button.dataset.range === "1W");
  });

  render();
  $("search-input").value = "";
  closeResults();
}

function closeResults() {
  const box = $("search-results");
  box.classList.remove("open");
  box.innerHTML = "";
}

function runSearch(query) {
  const box = $("search-results");
  const q = query.trim().toLowerCase();

  if (!q) {
    closeResults();
    return;
  }

  const matches = Object.values(allStocks)
    .filter((stock) =>
      String(stock.ticker).toLowerCase().includes(q) ||
      String(stock.company).toLowerCase().includes(q)
    )
    .slice(0, 20);

  if (matches.length === 0) {
    box.innerHTML = '<div class="no-match">No matching DSE stock found</div>';
  } else {
    box.innerHTML = matches.map((stock) =>
      '<button class="result" type="button" data-ticker="' +
      escapeHTML(stock.ticker) +
      '">' +
      '<span>' + escapeHTML(stock.ticker) + '</span>' +
      '<span class="name">' + escapeHTML(stock.company) + '</span>' +
      '</button>'
    ).join("");

    box.querySelectorAll(".result").forEach((el) => {
      el.addEventListener("click", () => selectStock(el.dataset.ticker));
    });
  }

  box.classList.add("open");
}

$("search-input").addEventListener("input", (event) => {
  runSearch(event.target.value);
});

document.addEventListener("click", (event) => {
  if (!event.target.closest(".search")) closeResults();
});

function formatNumber(value, decimals = 2) {
  const number = Number(value);
  return Number.isFinite(number)
    ? number.toLocaleString("en-BD", {
        minimumFractionDigits: decimals,
        maximumFractionDigits: decimals,
      })
    : "—";
}

function formatInteger(value) {
  const number = Number(value);
  return Number.isFinite(number)
    ? number.toLocaleString("en-BD", { maximumFractionDigits: 0 })
    : String(value ?? "—");
}

function render() {
  if (!currentData) return;

  const d = currentData;
  $("stock-ticker").textContent = d.ticker + " · " + d.company;
  $("stock-price").textContent = "৳ " + formatNumber(d.price);

  const changeEl = $("stock-change");
  const up = Number(d.change) >= 0;
  changeEl.textContent =
    (up ? "▲ " : "▼ ") + formatNumber(Math.abs(d.change)) +
    " (" + formatNumber(Math.abs(d.change_pct)) + "%) today";
  changeEl.className = "change " + (up ? "up" : "down");

  const updatedAt = $("last-updated").dataset.updatedAt;
  $("last-updated").textContent = updatedAt
    ? "Updated " + new Date(updatedAt).toLocaleString()
    : "";

  const stats = [
    ["Open", "৳ " + formatNumber(d.open)],
    ["High", "৳ " + formatNumber(d.high)],
    ["Low", "৳ " + formatNumber(d.low)],
    ["Prev. Close", "৳ " + formatNumber(d.prev_close)],
    ["Volume", formatInteger(d.volume)],
    ["Value (mn)", "৳ " + formatNumber(d.value_mn)],
  ];

  $("stats-grid").innerHTML = stats.map(([label, value]) =>
    '<div class="stat"><div class="label">' + label +
    '</div><div class="value">' + value + '</div></div>'
  ).join("");

  drawChart();
}

function drawChart() {
  const series = currentData?.history?.[currentRange];
  const line = $("chart-line");
  const empty = $("chart-empty");

  if (!series || series.length < 2) {
    line.setAttribute("points", "");
    empty.hidden = false;
    return;
  }

  empty.hidden = true;

  const values = series.map((point) => Number(point[1]));
  const min = Math.min(...values);
  const max = Math.max(...values);
  const range = max - min || 1;
  const w = 600, h = 180, pad = 10;

  const points = series.map((point, index) => {
    const x = (index / (series.length - 1)) * w;
    const y = h - pad - ((Number(point[1]) - min) / range) * (h - pad * 2);
    return x.toFixed(1) + "," + y.toFixed(1);
  }).join(" ");

  line.setAttribute("points", points);
}

document.querySelectorAll(".range-tabs button").forEach((button) => {
  button.addEventListener("click", () => {
    document.querySelectorAll(".range-tabs button")
      .forEach((b) => b.classList.remove("active"));

    button.classList.add("active");
    currentRange = button.dataset.range;
    drawChart();
  });
});

loadData();
setInterval(loadData, 5 * 60 * 1000);